#!/usr/bin/env python3
"""Drive MCP Registry publishing across all portfolio server repos.

This orchestrates the tedious, repeated parts of getting every server into the
official MCP Registry (https://registry.modelcontextprotocol.io), starting from
the drafts in ``registry/<id>/server.json`` (generated by
``scripts/generate_server_json.py``).

For each (selected) server it:

  1. resolves the **published PyPI version** for the package identifier,
  2. produces a **publish-ready** ``server.json`` with that version filled in,
  3. flags **blockers** that would make ``mcp-publisher publish`` fail:
       * the package is not on PyPI yet,
       * the PyPI metadata does not declare the matching ``mcp-name``,
  4. optionally writes the file into each repo working copy and runs
     ``mcp-publisher publish``.

It NEVER edits the committed ``registry/*/server.json`` drafts (those are pinned
to version 0.1.0 and checked in CI). Publish-ready copies go to ``dist/registry``
and/or into each server's own repo.

Safe by default: with no flags it does a **dry run** — resolve, validate, write
publish-ready copies to ``dist/registry``, and print a readiness table. Nothing
is published and no repo is touched until you pass ``--publish``.

Examples
--------
    # Dry run: readiness report for all 34 servers (writes dist/registry/*).
    python scripts/publish_registry.py

    # Same, just one server.
    python scripts/publish_registry.py --only swiss-transport-mcp

    # Clone/refresh every repo as a sibling dir, then publish the ready ones.
    python scripts/publish_registry.py --repos-dir ../repos --clone --publish

Prerequisites for --publish (per the registry docs, see registry/README.md):
  * each package published to PyPI with an ``mcp-name`` URL in pyproject.toml,
  * the ``mcp-publisher`` CLI installed and ``mcp-publisher login github`` done.
"""
from __future__ import annotations

import argparse
import json
import pathlib
import shutil
import subprocess
import sys
import urllib.error
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parent.parent
PORTFOLIO = ROOT / "portfolio.json"
REGISTRY_DIR = ROOT / "registry"
DEFAULT_OUT = ROOT / "dist" / "registry"
PYPI_JSON = "https://pypi.org/pypi/{identifier}/json"

# Per-server outcome states.
READY = "READY"
NOT_ON_PYPI = "NOT_ON_PYPI"
MISSING_MCP_NAME = "MISSING_MCP_NAME"
LOOKUP_ERROR = "PYPI_LOOKUP_ERROR"


def load_portfolio() -> dict:
    return json.loads(PORTFOLIO.read_text(encoding="utf-8"))


def repo_url_by_id(data: dict) -> dict[str, str]:
    return {s["id"]: s["repository"] for s in data["servers"]}


def load_drafts() -> list[tuple[str, dict]]:
    """(server_id, draft dict) for every committed registry draft, sorted."""
    out = []
    for path in sorted(REGISTRY_DIR.glob("*/server.json")):
        out.append((path.parent.name, json.loads(path.read_text(encoding="utf-8"))))
    return out


def pypi_info(identifier: str, timeout: float) -> dict | None:
    """Latest PyPI release info for ``identifier``; None if the project is 404."""
    url = PYPI_JSON.format(identifier=identifier)
    req = urllib.request.Request(url, headers={"Accept": "application/json"})
    try:
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            return json.loads(resp.read().decode("utf-8"))
    except urllib.error.HTTPError as exc:
        if exc.code == 404:
            return None
        raise


def declares_mcp_name(info: dict, expected_name: str) -> bool:
    """Whether the PyPI metadata advertises the registry name (ownership link)."""
    meta = info.get("info", {})
    urls = meta.get("project_urls") or {}
    # Convention: a project URL labelled 'mcp-name' carries the registry name.
    for key, val in urls.items():
        if key.strip().lower() == "mcp-name" and str(val).strip() == expected_name:
            return True
    # Fallback: some packages embed `mcp-name: <name>` in the long description.
    description = meta.get("description") or ""
    return f"mcp-name: {expected_name}" in description


def publish_ready(draft: dict, version: str) -> dict:
    """Copy of the draft with top-level + package version pinned to ``version``."""
    ready = json.loads(json.dumps(draft))  # deep copy
    ready["version"] = version
    for pkg in ready.get("packages", []):
        pkg["version"] = version
    return ready


def ensure_repo(repo_dir: pathlib.Path, url: str, clone: bool) -> bool:
    """Make sure the repo is present (clone/refresh when asked). Returns presence."""
    if repo_dir.exists():
        if clone:
            subprocess.run(["git", "-C", str(repo_dir), "pull", "--ff-only"], check=False)
        return True
    if not clone:
        return False
    repo_dir.parent.mkdir(parents=True, exist_ok=True)
    print(f"  cloning {url} -> {repo_dir}")
    res = subprocess.run(["git", "clone", "--depth", "1", url, str(repo_dir)], check=False)
    return res.returncode == 0


def run_publisher(repo_dir: pathlib.Path) -> bool:
    print(f"  publishing from {repo_dir} ...")
    res = subprocess.run(["mcp-publisher", "publish"], cwd=str(repo_dir), check=False)
    return res.returncode == 0


def serialize(obj: dict) -> str:
    return json.dumps(obj, indent=2, ensure_ascii=False) + "\n"


def parse_args(argv: list[str]) -> argparse.Namespace:
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--only", nargs="+", metavar="ID", help="restrict to these server ids")
    p.add_argument("--repos-dir", type=pathlib.Path, default=ROOT.parent,
                   help="directory containing server repos as <id>/ (default: parent of this repo)")
    p.add_argument("--clone", action="store_true",
                   help="git clone missing repos (and ff-pull existing ones)")
    p.add_argument("--out", type=pathlib.Path, default=DEFAULT_OUT,
                   help=f"where to write publish-ready server.json (default: {DEFAULT_OUT.relative_to(ROOT)})")
    p.add_argument("--publish", action="store_true",
                   help="actually run `mcp-publisher publish` for READY servers (default: dry run)")
    p.add_argument("--timeout", type=float, default=15.0, help="PyPI request timeout in seconds")
    return p.parse_args(argv)


def main(argv: list[str]) -> int:
    args = parse_args(argv)
    data = load_portfolio()
    urls = repo_url_by_id(data)
    drafts = load_drafts()
    if args.only:
        wanted = set(args.only)
        drafts = [(sid, d) for sid, d in drafts if sid in wanted]
        missing = wanted - {sid for sid, _ in drafts}
        if missing:
            print(f"ERROR: unknown server id(s): {', '.join(sorted(missing))}", file=sys.stderr)
            return 2

    if args.publish and not shutil.which("mcp-publisher"):
        print("ERROR: --publish given but `mcp-publisher` is not on PATH.\n"
              "       Install it and run `mcp-publisher login github` first "
              "(see registry/README.md).", file=sys.stderr)
        return 2

    args.out.mkdir(parents=True, exist_ok=True)
    rows: list[tuple[str, str, str]] = []  # (id, status, detail)
    published = 0

    for sid, draft in drafts:
        name = draft.get("name", f"?/{sid}")
        identifier = draft["packages"][0]["identifier"] if draft.get("packages") else sid
        print(f"\n== {sid} ({name})")

        # 1. Resolve PyPI version.
        try:
            info = pypi_info(identifier, args.timeout)
        except Exception as exc:  # noqa: BLE001 - network is best-effort, report per server
            rows.append((sid, LOOKUP_ERROR, str(exc)))
            print(f"  PyPI lookup failed: {exc}")
            continue
        if info is None:
            rows.append((sid, NOT_ON_PYPI, f"pip package '{identifier}' not found"))
            print(f"  not on PyPI yet: {identifier}")
            continue
        version = info["info"]["version"]
        print(f"  PyPI version: {version}")

        # 2. Write the publish-ready copy (always, even if blocked, for inspection).
        ready = publish_ready(draft, version)
        out_file = args.out / sid / "server.json"
        out_file.parent.mkdir(parents=True, exist_ok=True)
        out_file.write_text(serialize(ready), encoding="utf-8")

        # 3. Determine blockers.
        blockers = []
        if not declares_mcp_name(info, name):
            blockers.append(MISSING_MCP_NAME)
        if blockers:
            detail = "; ".join(blockers)
            rows.append((sid, "BLOCKED", detail))
            print(f"  blocked: {detail}")
            continue

        # 4. Stage into the repo and optionally publish.
        repo_dir = (args.repos_dir / sid).resolve()
        present = ensure_repo(repo_dir, urls.get(sid, ""), args.clone)
        if present:
            (repo_dir / "server.json").write_text(serialize(ready), encoding="utf-8")
            print(f"  staged server.json into {repo_dir}")
        elif args.publish:
            rows.append((sid, "NO_REPO", f"{repo_dir} missing (use --clone)"))
            print(f"  repo not found: {repo_dir} (use --clone)")
            continue

        if args.publish and present:
            ok = run_publisher(repo_dir)
            rows.append((sid, "PUBLISHED" if ok else "PUBLISH_FAILED", version))
            published += int(ok)
        else:
            rows.append((sid, READY, version))

    # Summary.
    print("\n" + "=" * 60)
    print(f"{'SERVER':<32} {'STATUS':<18} DETAIL")
    print("-" * 60)
    for sid, status, detail in rows:
        print(f"{sid:<32} {status:<18} {detail}")
    ready_n = sum(1 for _, s, _ in rows if s == READY)
    print("-" * 60)
    if args.publish:
        print(f"published {published} / {len(rows)} servers")
    else:
        print(f"{ready_n} ready to publish (dry run). Re-run with --publish to ship.")
    print(f"publish-ready files: {args.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
